:toc: macro

include::Titul_Lection4.adoc[]

toc::[]

== Задачи

Разобраться с типами данных в C++, и чем они отличаются друг от друга.

== Типы данных

В данной лекции я узнал, что различные встроенные типы могут иметь различную длину, например float может иметь длину 24 бит или стандартные 32. Так же узнал, что для размеров типов существует следующее правило:

[source,cpp]
----
1             <= sizeof(char)     <= sizeof(short) <= sizeof(int) <= sizeof(long)
1             <= sizeof(bool)     <= sizeof(long)
sizeof(char)  <= sizeof(long)
sizeof(float) <= sizeof(double)   <= sizeof(long double)
sizeof(T)     == sizeof(signed T) == sizeof(unsigned T)
----

Для присвоения типа данных лучше использовать псеводонимы, чтобы точно определить размер переменной:

[source,cpp]
using t = std::tuple<int, string, float_32t, tU32>; 
...
main()
{
    using float_32t = float;
    float_32t f = 12.9f;
}

Есть явное преобразование типов. Для преобразований из одного типа используют 4 вариантов преобразования:

* static_cast

* const_cast

* reinterpret_cast

* dynamic_cast

=== static_cast 

static_cast производит преобразование близких типов, например:

[source,cpp]
----
float f = static_cast<float>(8.89);
float g = 8.89f; 
----

В первым случае было произведено явное преобразование из double во float при помощи "static_cast", во втором случае при помощи литерала "f" было записано число уже в формате float.

=== reinterpret_cast

reinterpret_cast производит преобразование различных типов, преобразование, которых не может произойти даже в неявном виде, указатель в целое число, например:

[source,cpp]
----
auto ptr = reinterpret_cast<uint32_t *>(0x8000000); 
----

В данном случае было произведено преобразование адреса в указатель типа uint32_t. Так же можно сделать и обратную операцию.

== Выводы

В данной работе было проведено изучение оссобеностей типов данных микроконтроллеров на языке C++. Узнал 2 способа, как можно явно преобразовывать типы: 1-ый – static_cast, явно преобразует близкие типы; 2-ой – reinterpret_cost, преобразует типы, которые несовместимы друг с другом.