:toc: macro

include::Titul_Lection9.adoc[]

toc::[]

== Задачи

Разобрать принцип SOLID. Реализовать "ёлочку" и "шахматный режим" на светодиодах через классы.

== SOLID

*S: Single Responsibility Principle (Принцип единственной ответственности).* Класс должен быть ответственен лишь за что-то одно. Если класс отвечает за решение нескольких задач, его подсистемы, реализующие решение этих задач, оказываются связанными друг с другом. Изменения в одной такой подсистеме ведут к изменениям в другой.

*O: Open-Closed Principle (Принцип открытости-закрытости).* Программные сущности (классы, модули, функции) должны быть открыты для расширения, но не для модификации.

*L: Liskov Substitution Principle (Принцип подстановки Барбары Лисков).* Необходимо, чтобы классы-наследники могли бы использоваться вместо родительских классов, от которых они образованы, не нарушая работу программы.

*I: Interface Segregation Principle (Принцип разделения интерфейса).* Клиентов не следует заставлять зависеть от интерфейсов, которые они не используют.

*D: Dependency Inversion Principle (Принцип инверсии зависимостей).* Объектом зависимости должна быть абстракция, а не что-то конкретное.

== Ёлочка и шахматный режим

.ipin.h

[source,cpp]
----
#ifndef IPIN
#define IPIN

class IPin
{
public:
  virtual void Toggle() const = 0;
};

#endif
----

.pin.h

[source,cpp]
----
#ifndef PIN
#define PIN

#include "gpioaregisters.hpp" // for GPIOA
#include "gpioaregisters.hpp" // for GPIOC
#include "ipin.h" // for GPIOC

template<typename Port, int pinNumber>
class Pin : public IPin
{
public:
void Toggle() const override
{
  Port::ODR::Toggle(1 << pinNumber);  
}
};

#endif
----

.imode.h

[source,cpp]
----
#ifndef IMODE
#define IMODE

class IMode
{
public:
  virtual void Update() = 0;
};

#endif
----

.treemode.h

[source,cpp]
----
#ifndef TREEMODE 
#define TREEMODE

#include "gpioaregisters.hpp" // for GPIOA
#include "gpioaregisters.hpp" // for GPIOC
#include "imode.h"
#include <array>

template<auto& ... pins>
class TreeMode : public IMode
{
public:
void Update() override
{  
  leds[i++]->Toggle();
  if(i == leds.size())
  {
    i = 0;
  }
}
private:
  std::size_t i = 0;
  std::array<IPin*, sizeof ... (pins)> leds = {static_cast<IPin*> (&pins)...};
};

#endif
----

.chessmode.h

[source,cpp]
----
#ifndef CHESSMODE
#define CHESSMODE

#include "gpioaregisters.hpp" // for GPIOA
#include "gpioaregisters.hpp" // for GPIOC
#include "imode.h"
#include <array>

template<auto& ... pins>
class ChessMode : public IMode
{
private:
  int i = 0;
  bool flag = false;
  std::array<IPin*, sizeof ... (pins)> leds = {static_cast<IPin*> (&pins)...};
public:
  /*ChessMode()
  {
    for(i = 0; i < leds.size(); i+=2)
    {
      leds[i]->Toggle();
    }
  }*/
  void Update() override
  {
    if(!flag)
    {
      for(i = 0; i < leds.size(); i+=2)
      {
        leds[i]->Toggle();
      }
    } else if(flag)
    {
      for(auto it: leds)
      {
        it->Toggle();
      }
    }
    flag = true;
  }
};

#endif
----

.main.cpp

[source,cpp]
----
#include "rccregisters.hpp" // for RCC
#include "gpioaregisters.hpp" // for GPIOA
#include "gpiocregisters.hpp" // for GPION
#include "pin.h"
#include "treemode.h"
#include "chessmode.h"

std::uint32_t SystemCoreClock = 16'000'000U;

void delay(int cycles)
{
  for(int i = 0; i < cycles; ++i)    
  {   
    asm volatile("");
  }    
}

Pin<GPIOC, 5> pin1;
Pin<GPIOC, 8> pin2;
Pin<GPIOC, 9> pin3;
Pin<GPIOA, 5> pin4;

TreeMode<pin1, pin2, pin3, pin4> el; //Создание объекта класса режим елочки
ChessMode<pin1, pin2, pin3, pin4> chess; //Создание объекта класса шахматный режим

int main()
{
  RCC::AHB1ENR::GPIOAEN::Enable::Set(); //Подача тактирования на порт A
  RCC::AHB1ENR::GPIOCEN::Enable::Set(); //Подача тактирования на порт C
  GPIOA::MODER::MODER5::Output::Set(); //Порт A.5 на вывод
  GPIOC::MODER::MODER5::Output::Set(); //Порт С.5 на вывод
  GPIOC::MODER::MODER8::Output::Set(); //Порт С.8 на вывод
  GPIOC::MODER::MODER9::Output::Set(); //Порт С.9 на вывод
  
  for(;;)
  {
    el.Update(); // Включение елочки
    //chess.Update(); // Включение шахматного режима
    delay(1000000);
  }
  
  return 1;
}
----

В результате получилось следующее.

.Работа "ёлочки"
video::Video/Elochka.mov[]

.Работа "шахматного режима"
video::Video/Chess.mov[]

== Выводы

В данной работе было разобрано, что такое принципы SOLID. Реализована "ёлочка" и "шахматный режим" через классы, с соблюдением принципов SOLID.