:toc: macro

include::Titul_Lection6.adoc[]

toc::[]

== Задачи

Разобрать, что такое регистры и как с ними работать.

== Регистры

Регистр – очень быстрая память, содержащаяся в микроконтролере, она используется для хранения значений или адресов переменных (*_регистр общего назначения_*) или для работы/управления микроконтроллером или его перефирии (АЦП, таймеры и т.д.) (*_регистр специального назначения_*).

=== Регистры общего назначения

Регистры общего назначения подразделяются на 3 типа, в зависимости от их функций:

* *Оперативные регистры.* Любая функция может использовать эти регистры так, как ей необходимо. Если после того, как вызвалась новая функция, предыдущей функции нужны значения, хранящиеся в этих регистрах, то они сохраняются на стеке.
* *Вспомогательные регистры.* Любая функция должна сохранить их на входе, а при выходе восстановить их значение.
* *Специальные регистры.* В данном регистре содержатся: указатель на стек (SP), адрес возврата функций (LR), программный счетчик (PC).  

=== Регистры специального назначение

Регистры специального назначения обозначены 32-битным шестастнадцатеричным числом, у них есть поля с ячейками, в свою очередь каждое поле имеет свою длину. Если поле имеет длину 2 бита, то существует 4 возможные значения поля. Так же поля имееют свой режим доступа (чтение, запись, чтение и запись).

Пример работы с регистром:

.main.cpp

[source,cpp]
----
#include "rccregisters.hpp" // for RCC
#include "gpiocregisters.hpp" // for GPIOС

std::uint32_t SystemCoreClock = 16'000'000U;

extern "C" {
int __low_level_init(void)
{
}
}

void delay(int cycles)
{
  for(int i = 0; i < cycles; ++i)    
  {   
    asm volatile("");
  }    
}

int main()
{
  //Подача тактирования на порт C
  RCC::AHB1ENR::GPIOCEN::Enable::Set();
  //Порты C.5, C.8 на вывод
  GPIOC::MODER::MODER5::Output::Set();
  GPIOC::MODER::MODER8::Output::Set();
  //Подача на порт C.8 регистрыoutput data register (ODR) единицы, т.е. питания, с использованием обертки
  GPIOC::ODR::ODR8::High::Set();
  //Приведение адреса регистра ODR порта С.5 к указателю
  std::uint32_t* ptr = reinterpret_cast<std::uint32_t*>(0x40020014);
  for(;;)
  {
    //Подача на порт С.5 регистра ODR единицы, с использованием алгебры логики
     *ptr |= (1U << 5U);
     delay(1000000);
     //Отключение на порт С.5 регистра ODR единицы, с использованием алгебры логики
     *ptr &=~ (1U << 5U);
     delay(1000000); 
  }
  
  return 1;
}
----

В результате диод, который связан с портом C.8 будет светиться, а диод, связанный с портом C.5 будет моргать. 

.Работа кода
video::Work with R.mov[]

== Выводы

В данной работе было разобрано, что такое регистры, какие бывают типы регистров, как получить доступ к регистрам и  как с ними работать при помощи обертки и алгебры логики.