= Отчёт
== Запуск ПО
При подаче питания на микроконтроллер, первым делом он переходит по адресу таблицы векторов прерываний (микроконтроллер STM32F411RE по умолчанию переходит по адресу 0x800'0000)
Далее инициализуется стек. Стек представляет собой область памяти, которую ядро микроконтроллера использует для хранения временных значений, временные значения из стека берутся в обратном порядке, размер стека можно менять, чтобы, например, не случилось переполнения. Адрес памяти последнего элемента хранится в указателе стека
На следующем этапе происхоlит инициализация ядра и нулевых, а затем ненулевых переменных. Нулевые переменные – глобальные или статические переменные, которым не присвоено значение, например, int i. Ненулевые переменные – переменные, которым присвоено значение, например, int i = 1
Далее запускается функция main(). Функция main — это место, где начинается выполнение исходного кода
Переход между этипи этапами осуществляет счетчик программ – регистр, указывающий адрес следующей комманды, функции. Он увеличивает адрес на 1, в случае с STM32F411RE на 4 байта
== Вопросы по разделу
. Дайте определения понятию "интегрированная среда разработки"
Интегрированная среда разработки – программное приложение, которое помогает программистам разрабатывать, проверять программный код.
. Что такое компилятор и чем он отличается от транслятора?
Компилятор – транслятор, преобразующий програмнный код в машинный. Компилятор переводит исходный код только в машинный код, транслятор может переводить и в другой код
. Что такое компоновщик и какие функции он выполняет?
Компоновщик предназначен для связывания между собой объектных скомпилированных файлов, а также файлов библиотек, входящих в состав системы программирования, в один исполняемый файл
. Почему важен процесс проектирования ПО какие задачи входят в этот процесс?
Определив требования к программному обеспечению, разработчик получает согласованный четкий план действий, примерную картинку, которая должна получиться на выходе и совпасть с картинкой заказчика, примерные сроки, бюджет и т.п. Так же этот процесс важен, так как если ошибится на этом процессе, то это приведёт к большим убыткам по времени на следующих стадиях и возможно придётся начинать всё заново
. Зачем нужна отладка и в каких случаях она применяется? Для чего применяются точки остановки?
Отладка позволяет находить и исправлять ошибки в коде, улучшать его производительность и эффективность. Точка остановы – место в коде, на котором процесс выполнения программы приостанавливается, использую их можно понять до какого места работает программа или работает ли программа в определённом месте
