:toc: macro

include::Titul_Lection12.adoc[]

toc::[]

== Задачи

Рассмотреть для чего используются таймеры, их виды. Написать код для переключения светодиодов с периодом 500 мс, при нажатии на кнопку период увеличивается на 100 мс вплоть до 1000 мс и после всё по кругу, использовать таймер TIM5.

== Таймеры

Таймеры нужны для точного отсчета времени, измерения частоты/периода, генерации ШИМ (широтно-импульсной модуляции) и переменных сигналов. Всего есть следующие виды таймеров:

* SYSTEM TIMER. Также существуют системный таймер SysTick таймер и Watchdog таймер.

* TIM1. Это расширенный 16 битный таймер автоматической перезагрузки, приводимого в действие
программируемым прескалером.

* TIM2–TIM5. 16-разрядные (TIM3, TIM4) или 32-разрядные (TIM2, TIM5) таймеры общего назначения автоматической перезагрузки, приводимого в действие
программируемым прескалером.

*TIM9–TIM11. Самые обычные 16-разрядные таймеры общего назначения TIM9/10/11 автоматической перезагрузки, приводимого в действие программируемым прескалером.

=== TIM2 и TIM5

Таймеры 32 битные (то есть могут считать до 2^32), умеют работать:

* с инкрементальными энкодерами и датчиками Холла;

* несколько таймеров можно синхронизировать между собой.

Таймеры могут использоваться для:

* захвата сигнала (Защелкивать значение, когда на выводе порта например 0 сменился на 1);

* сравнения (Считать до значения в регистре сравнения и установить/сбросить/переключить вывод порта);

* генерации ШИМ (Генерировать прямоугольный сигнал с различной скважностью на вывод порта);

* генерации одиночного импульса.

*Для организации задержки*:

. Подать тактирование на модуль таймера​

. Установить делитель частоты для таймера в регистре PSC​

. Установить источник генерации прерываний по событию переполнение с помощью бита URS в регистре CR1​

. Установить значение до которого счетчик будет считать в регистре перезагрузке ARR​

. Скинуть флаг генерации прерывания UIF по событию в регистре SR​

. Установить начальное значение счетчика в 0 в регистре CNT​

. Запустить счетчик с помощью бита EN в регистре CR1​

. Проверять, пока не будет установлен флаг генерации прерывания по событию UIF в регистре SR​

. Как только флаг установлен, остановить счетчик, сбросить бит EN в регистре CR1. Сбросить флаг генерации прерывания UIF по событию в регистре SR

== Код моргания светодиодами с использованием задержки в виде TIM5

.main.c

[source,cpp]
----
#include "rccregisters.hpp" // for RCC
#include "gpioaregisters.hpp" // for GPIOA
#include "gpiocregisters.hpp" // for GPIOC
#include "tim5registers.hpp"
#include "pin.h"
#include "allmode.h"
#include "button.h"

std::uint32_t SystemCoreClock = 16'000'000U;
std::uint32_t Tim2 = 1'000'000U;

extern "C" {
int __low_level_init(void)
{
  RCC::APB1ENR::TIM5EN::Enable::Set();
  return 1;
}
}

using tMsec = std::uint32_t;

void delay(tMsec period)
{
  const auto timerValue = static_cast<uint32_t>(((period)*(Tim2/1000U))-1U);
  const auto psc = static_cast<uint32_t>(SystemCoreClock/1000000U-1U);
  TIM5::PSC::Write(psc);
  TIM5::CR1::URS::Value1::Set();
  TIM5::ARR::Write(timerValue);
  TIM5::SR::UIF::Set(0);
  TIM5::CNT::Write(0);
  int h = TIM5::CNT::Get();
  
  TIM5::CR1::CEN::Enable::Set();
  while(TIM5::SR::UIF::Get() == 0)
  {
  }
  TIM5::CR1::CEN::Disable::Set();
  TIM5::SR::UIF::Set(0);
}

Pin<GPIOC, 5> pin1;
Pin<GPIOC, 8> pin2;
Pin<GPIOC, 9> pin3;
Pin<GPIOA, 5> pin4;

Button<GPIOC, 13> btn;

AllMode<pin1, pin2, pin3, pin4> all; //Создание объекта класса режим "все"

  int main()
{
  RCC::AHB1ENR::GPIOAEN::Enable::Set(); //Подача тактирования на порт A
  RCC::AHB1ENR::GPIOCEN::Enable::Set(); //Подача тактирования на порт C
  //GPIOC::MODER::MODER13::Input::Set(); //Порт C.13 на ввод
  GPIOA::MODER::MODER5::Output::Set(); //Порт A.5 на вывод
  GPIOC::MODER::MODER5::Output::Set(); //Порт С.5 на вывод
  GPIOC::MODER::MODER8::Output::Set(); //Порт С.8 на вывод
  GPIOC::MODER::MODER9::Output::Set(); //Порт С.9 на вывод

  tMsec i = 500U;
  for(;;)
  { 
    all.Update();
    if(btn.IsPressed())
    {
      i = (i<tMsec(1000)) ? (i+tMsec(100U)) : tMsec(500U) ;
    }
    delay(i);
  }
  
  return 1;
}
----

.Работа кода
video::Video/Result_TIM5.mp4[]

== Выводы

В данной работе были рассмотрены виды таймеров, описан функционал таймеров TIM2 и TIM5, и как с ними работать в режиме счетчика. По итогу был написан код для работы таймера TIM5 для переключения светодиодов с периодом 500 мс, при нажатии на кнопку период увеличивается на 100 мс вплоть до 1000 мс, и после следующего нажатия период становиться 500 мс и всё начинается заново.